### ISSUE TITLE
Is it possible to run under windows+ python + CUDA?

### ISSUE THREAD

**Issue by blackcement** [IlyaGusev/rulm#20]
Is it possible to run under windows?

**Comment by Andrew-MK** [comment]
Yes, of course. Download [Saiga llamacpp model](https://huggingface.co/IlyaGusev/saiga_7b_lora_llamacpp) and inference them with windows (win) version [kobold](https://github.com/LostRuins/koboldcpp/releases) or [llama.cpp](https://github.com/ggerganov/llama.cpp/releases/tag/master-fff0e0e) or [llama-cpp-python](https://github.com/abetlen/llama-cpp-python/releases) by following intructions from the documentation of this software.

**Comment by blackcement** [comment]
@Andrew-MK , Thank you! I meant a little different, I would like to run in win + python + CUDA, sorry for the inaccuracy, I corrected the title

**Comment by Andrew-MK** [comment]
The venerable author of Saiga, Ilya, has provided us with two ways to do this:

Method 1 (simple). Install [CUDA Toolkit 11.7](https://developer.nvidia.com/cuda-11-7-0-download-archive) then [pytorch for cuda 11.7](https://pytorch.org/get-started/locally/) then instal other modules - pip install sentencepiece accelerate  bitsandbytes transformers peft then use [saiga_7b_lora](https://huggingface.co/IlyaGusev/saiga_7b_lora) Saiga version and example code.

Method 2. Install CUDA 11.7-12.2 then install microsoft Visual Studio and compile [llama-cpp-python](https://github.com/abetlen/llama-cpp-python/) for your python and CUDA and install compiled package. Then  use [saiga_7b_lora_llamacpp](https://huggingface.co/IlyaGusev/saiga_7b_lora_llamacpp) Saiga version and example code (add GPU offloading into call of function for load the model: model = Llama(...n_gpu_layers=100,...) ). If you can't compile on your own, then here are the packages for python 3.7 or python 3.10 with CUDA 11.7 support: [llama_cpp_python-0.1.75-windows-cuda-11.7.zip](https://github.com/IlyaGusev/rulm/files/12134071/llama_cpp_python-0.1.75-windows-cuda-11.7.zip) - just install it with pip install packet.whl and use above model with example.
