### ISSUE TITLE
Why results are much worse on V100? 

### ISSUE THREAD

**Issue by igroboy** [IlyaGusev/rulm#24]
Why results of Saiga 2 are much worse on V100? I tried inference model on V100, and indeed results sucks. What's the reason? And can I somehow fix it?

**Comment by Andrew-MK** [comment]
- Это правда происходит из-за старой V100 архитектуры, так как LLaMA2 на A100 обучалась - т.е. проблемы могут быть еще и на 2080, T4..., в том числе с gglm версиями с офлодом на GPU и даже при запуске на CPU?
- По приведенной таблице Toloka в целом неясно, лучше ли Saiga2 вышла, чем первая Saiga:
saiga7b vs saiga2_7b: 78-8-90
saiga13b vs saiga2_13b: 95-2-79
Т.е. 7b вышла лучше, а 13b хуже прежней Сайги (а что по середине цифра значит)? По моим замерам на своих промптах на не полном RussianSuperGlue Сайга2 всё же меньшие очки набирает, её поэтому пока нет в таблице https://github.com/IlyaGusev/rulm#rsg?
