### ISSUE TITLE
Mistral 7B - лучше в русском чем saiga2_7b

### ISSUE THREAD

**Issue by NeuralAIM** [IlyaGusev/rulm#30]
Похоже есть хороший кандидат к #26 

На удивление гораздо меньше орфографических ошибок. Достаточно хорошо ведет диалог на русском.

> Хотелось бы увидеть эту модель дообученую на данных saiga.

Можно проверить [Здесь](https://huggingface.co/spaces/Open-Orca/Mistral-7B-OpenOrca) 

[Ссылка на модель](https://huggingface.co/Open-Orca/Mistral-7B-OpenOrca)

**Comment by IlyaGusev** [comment]
Сделано!

https://huggingface.co/IlyaGusev/saiga_mistral_7b_lora
